;; clj-intro - Introduction to Clojure
;; https://github.com/egalli64/clj-intro
;;
;; For more info read Getting Clojure by Russ Olsen
;; partial

;; my first version of the standard function inc
(defn my-inc [n] (+ n 1))
(my-inc 41)

;; revised version, defining it as a partial of +
;; the symbol my-inc is bound to the function generated by partial on + passing 1 as argument
(def my-inc (partial + 1))
(my-inc 41)
